# Setup
title: 'the missing semester of your cs education'
url: https://missing.csail.mit.edu

# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true
# safe: true # breaks local rendering if enabled
timezone: America/New_York
analytics:
  tracking_id: UA-53167467-11

# Excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
